export default function LocalDataExample() {
  return <section className="container px-4 pt-12 md:pt-16">
    <div className="max-w-5xl mx-auto">
      <p className="text-xs uppercase tracking-wider text-brand-teal font-medium mb-3">Local knowledge, practical action</p>
      <h2 className="text-2xl md:text-3xl mb-4">Connect your AI to the businesses around you</h2>
      <p className="text-muted-foreground leading-relaxed max-w-3xl">The Startup Orillia MCP gives your AI access to our playbooks and local business information, so it can help you find potential partners, discover suppliers and prepare for events—not just suggest generic ideas.</p>
      <div className="grid sm:grid-cols-3 gap-4 mt-7">
        {[
          ["500+", "local businesses", "Search names, services, descriptions and published website links."],
          ["190+", "business categories", "Explore suppliers and potential partners by the work they do."],
          ["Local events", "with source links", "Look up dates and details captured from the public calendar."],
        ].map(([value, label, description]) => <div key={value} className="rounded-2xl border bg-card p-6"><p className="font-heading text-3xl text-brand-teal font-semibold mb-1">{value}</p><p className="font-medium mb-3">{label}</p><p className="text-sm text-muted-foreground leading-relaxed">{description}</p></div>)}
      </div>
      <p className="text-xs italic text-muted-foreground leading-relaxed mt-4">Snapshots are refreshed regularly. This is not a directory of every business in the area.</p>

      <details id="real-example" className="rounded-2xl border bg-card mt-7 group scroll-mt-24">
        <summary className="cursor-pointer p-6 font-heading text-xl font-semibold text-brand-orange">See an end-to-end example with real local data</summary>
        <div className="px-6 pb-6 md:px-8 md:pb-8 space-y-7">
          <p className="text-sm text-muted-foreground leading-relaxed">A worked example using the Startup Orillia MCP and skills, with real local search results from September 17, 2026. This shows how a campaign could work, not one that has already happened. The bakery, budget and sales goals are made up for this example. The named businesses have real listings, but have not agreed to take part.</p>
          <div><h3 className="font-heading text-lg font-semibold mb-2">1. Start with the business problem</h3><blockquote className="rounded-lg bg-secondary p-4">“I run a bakery in Orillia. January weekdays are slow. Help me increase sales.”</blockquote><p className="text-sm text-muted-foreground mt-3">Your AI reads the Local Marketing Campaign skill. It asks what you can spend and how many extra orders you can handle, then uses these example figures: a $300 test budget and a target of 20 extra weekday orders in 30 days.</p></div>
          <div><h3 className="font-heading text-lg font-semibold mb-2">2. Look for actual local possibilities</h3><p className="text-sm text-muted-foreground mb-4">The AI could compare office preorder boxes, a studio-to-bakery pickup offer and hotel guest orders. For the studio idea, a search through the Startup Orillia MCP for “gym” returned these listings:</p><div className="grid md:grid-cols-2 gap-4">
            <article className="rounded-xl border p-4"><p className="text-xs uppercase tracking-wide text-brand-teal mb-2">From the business listing</p><h4 className="font-semibold mb-2">ALIGN Yoga &amp; Pilates Studio</h4><p className="text-sm text-muted-foreground mb-3">Listed in Orillia under Gyms &amp; Fitness Centres. Its description mentions warm and hot yoga classes and education workshops.</p><a href="https://business.orillia.com/list/member/align-yoga-pilates-studio-1216" target="_blank" rel="noreferrer" className="text-sm text-brand-orange underline">Read the official listing</a></article>
            <article className="rounded-xl border p-4"><p className="text-xs uppercase tracking-wide text-brand-teal mb-2">From the business listing</p><h4 className="font-semibold mb-2">Nucleo Pilates &amp; Rowing</h4><p className="text-sm text-muted-foreground mb-3">Listed in Orillia under Gyms &amp; Fitness Centres. Its description mentions small-group Pilates, indoor rowing and barre.</p><a href="https://business.orillia.com/list/member/nucleo-pilates-rowing-1177" target="_blank" rel="noreferrer" className="text-sm text-brand-orange underline">Read the official listing</a></article>
          </div><p className="text-sm text-muted-foreground mt-3">An idea to test, not a fact from the listings: people leaving a class might enjoy picking up something from the bakery on their way home. Check the location, class times, food preferences and whether customers are interested before suggesting a partnership. Membership is not an endorsement or quality rating.</p></div>
          <div><h3 className="font-heading text-lg font-semibold mb-2">3. Say “Build the studio idea”</h3><p className="text-sm text-muted-foreground leading-relaxed">The AI suggests a two-week test. Customers order ahead and collect a simple bakery bundle at a set time on weekdays. Set the price after checking ingredient, packaging and staff costs. Give each participating studio its own code so you can see where orders come from. Only accept as many extra orders as you can handle. Get the studio’s agreement before offering a discount together, using its logo or announcing a partnership.</p></div>
          <div><h3 className="font-heading text-lg font-semibold mb-2">4. Get drafts you can actually use</h3><p className="text-sm font-medium mb-2">Example message for you to review and send</p><blockquote className="rounded-lg bg-secondary p-4 text-sm leading-relaxed">Hi ALIGN team—I'm the owner of [bakery]. I found your yoga classes through the local business directory. Would you be open to discussing a small weekday bakery pickup test for interested customers? We would handle preorders and pickup at our shop, and agree the offer and wording with you first. No customer list sharing needed. Is this something your customers might find useful?</blockquote><p className="text-sm font-medium mt-4 mb-2">Example message for customers, once the partner agrees</p><p className="text-sm text-muted-foreground">“Make your weekday a little sweeter. Preorder [bundle] for [price] and collect at [bakery] during [window]. Order by [deadline]. Ingredients and allergen information: [link].”</p></div>
          <div><h3 className="font-heading text-lg font-semibold mb-2">5. Leave with a 30-day plan and a decision</h3><ol className="list-decimal pl-5 space-y-2 text-sm text-muted-foreground"><li><strong className="text-foreground">Days 1–7:</strong> check costs and how many extra orders you can handle. Record your usual weekday orders and ask one possible partner whether the idea would work for them.</li><li><strong className="text-foreground">Days 8–14:</strong> if they agree, settle the offer, order codes, pickup details and wording together. Otherwise change the idea before spending money.</li><li><strong className="text-foreground">Days 15–28:</strong> run the test. Record orders using each code, sales, the cost of filling those orders, staff time and customer feedback.</li><li><strong className="text-foreground">Days 29–30:</strong> compare with normal weekdays. Aim for 20 extra orders and stay within $300. Continue only if the money earned is worth the cost and effort. Some customers using a code might have bought from you anyway, so do not count every code as an extra sale.</li></ol></div>
          <p className="text-sm text-muted-foreground border-t pt-5">That is the combination: a skill guides the work, the Startup Orillia MCP provides local information, and your AI helps turn it into drafts and decisions. You check the details, approve the plan and take action.</p>
          <a href="#setup" className="btn-primary inline-flex">Try it with your AI tool</a>
        </div>
      </details>
    </div>
  </section>;
}
