export default function LocalDataExample() {
  return <section className="container px-4 pt-12 md:pt-16">
    <div className="max-w-5xl mx-auto">
      <p className="text-xs uppercase tracking-wider text-brand-teal font-medium mb-3">Local knowledge, practical action</p>
      <h2 className="text-2xl md:text-3xl mb-4">Connect your AI to the businesses around you</h2>
      <p className="text-muted-foreground leading-relaxed max-w-3xl">The Startup Orillia MCP gives your AI access to our playbooks and local business information, so it can help you find potential partners, discover suppliers and prepare for events—not just suggest generic ideas.</p>
      <div className="grid sm:grid-cols-3 gap-4 mt-7">
        {[
          ["500+", "local businesses", "Search names, services, descriptions and published website links."],
          ["190+", "business categories", "Explore suppliers and potential partners by the work they do."],
          ["Local events", "with source links", "Look up dates and details captured from the public calendar."],
        ].map(([value, label, description]) => <div key={value} className="rounded-2xl border bg-card p-6"><p className="font-heading text-3xl text-brand-teal font-semibold mb-1">{value}</p><p className="font-medium mb-3">{label}</p><p className="text-sm text-muted-foreground leading-relaxed">{description}</p></div>)}
      </div>
      <p className="text-xs text-muted-foreground leading-relaxed mt-4">Counts rounded down from the September 17, 2026 snapshot: 513 listings, 197 categories and 10 calendar events. Our first local data source is publicly available <a href="https://business.orillia.com/" target="_blank" rel="noreferrer" className="underline">Orillia &amp; District Chamber of Commerce information</a>. Snapshots are refreshed monthly, not live; visit the official listings for the most accurate and up-to-date information. This is not a directory of every business in the area.</p>

      <details id="real-example" className="rounded-2xl border bg-card mt-7 group scroll-mt-24">
        <summary className="cursor-pointer p-6 font-heading text-xl font-semibold text-brand-orange">See an end-to-end example with real local data</summary>
        <div className="px-6 pb-6 md:px-8 md:pb-8 space-y-7">
          <p className="text-sm text-muted-foreground leading-relaxed">A worked example using real MCP search results from September 17, 2026—not a transcript or a completed campaign. The bakery, budget, targets and campaign below are illustrative. The named businesses are real listings; no participation, interest or endorsement is implied.</p>
          <div><h3 className="font-heading text-lg font-semibold mb-2">1. Start with the business problem</h3><blockquote className="rounded-lg bg-secondary p-4">“I run a bakery in Orillia. January weekdays are slow. Help me increase sales.”</blockquote><p className="text-sm text-muted-foreground mt-3">Your AI reads the Local Marketing Campaign skill. It asks what you can spend and how many extra orders you can handle, then works with explicit assumptions: a $300 test budget and a target of 20 extra weekday orders in 30 days.</p></div>
          <div><h3 className="font-heading text-lg font-semibold mb-2">2. Look for actual local possibilities</h3><p className="text-sm text-muted-foreground mb-4">The AI could compare office preorder boxes, a studio-to-bakery pickup offer and hotel guest orders. For the studio idea, a real MCP search for “gym” returned these listings:</p><div className="grid md:grid-cols-2 gap-4">
            <article className="rounded-xl border p-4"><p className="text-xs uppercase tracking-wide text-brand-teal mb-2">Sourced listing facts</p><h4 className="font-semibold mb-2">ALIGN Yoga &amp; Pilates Studio</h4><p className="text-sm text-muted-foreground mb-3">Listed in Orillia under Gyms &amp; Fitness Centres. Its description mentions warm and hot yoga classes and education workshops.</p><a href="https://business.orillia.com/list/member/align-yoga-pilates-studio-1216" target="_blank" rel="noreferrer" className="text-sm text-brand-orange underline">Read the official listing</a></article>
            <article className="rounded-xl border p-4"><p className="text-xs uppercase tracking-wide text-brand-teal mb-2">Sourced listing facts</p><h4 className="font-semibold mb-2">Nucleo Pilates &amp; Rowing</h4><p className="text-sm text-muted-foreground mb-3">Listed in Orillia under Gyms &amp; Fitness Centres. Its description mentions small-group Pilates, indoor rowing and barre.</p><a href="https://business.orillia.com/list/member/nucleo-pilates-rowing-1177" target="_blank" rel="noreferrer" className="text-sm text-brand-orange underline">Read the official listing</a></article>
          </div><p className="text-sm text-muted-foreground mt-3">Campaign hypothesis, not a listing fact: some class participants might enjoy a convenient bakery pickup on their way home. Check location, class times, customer interest and dietary preferences before proposing a fit. Membership is not an endorsement or quality rating.</p></div>
          <div><h3 className="font-heading text-lg font-semibold mb-2">3. Say “Build the studio idea”</h3><p className="text-sm text-muted-foreground leading-relaxed">The AI turns the idea into a two-week weekday preorder test: one bakery pickup window, one simple bundle priced after checking ingredient, packaging and labour costs, and a separate tracking code for any participating studio. Cap orders at spare capacity. Do not promise a discount, use a studio’s logo or announce a partnership without agreement.</p></div>
          <div><h3 className="font-heading text-lg font-semibold mb-2">4. Get drafts you can actually use</h3><p className="text-sm font-medium mb-2">Example outreach for you to review and send</p><blockquote className="rounded-lg bg-secondary p-4 text-sm leading-relaxed">Hi ALIGN team—I'm the owner of [bakery]. I found your yoga classes through the local business directory. Would you be open to discussing a small weekday bakery pickup test for interested customers? We would handle preorders and pickup at our shop, and agree the offer and wording with you first. No customer list sharing needed. Is this something your customers might find useful?</blockquote><p className="text-sm font-medium mt-4 mb-2">Example customer copy, only after agreement</p><p className="text-sm text-muted-foreground">“Make your weekday a little sweeter. Preorder [bundle] for [price] and collect at [bakery] during [window]. Order by [deadline]. Ingredients and allergen information: [link].”</p></div>
          <div><h3 className="font-heading text-lg font-semibold mb-2">5. Leave with a 30-day plan and a decision</h3><ol className="list-decimal pl-5 space-y-2 text-sm text-muted-foreground"><li><strong className="text-foreground">Days 1–7:</strong> check costs and capacity, record typical weekday orders, contact one possible partner and confirm fit.</li><li><strong className="text-foreground">Days 8–14:</strong> if a partner agrees, finalize terms, tracking, pickup details and approved copy. Otherwise revise the concept before spending.</li><li><strong className="text-foreground">Days 15–28:</strong> run the small test; record code-attributed orders, revenue, variable costs, staff time and customer feedback.</li><li><strong className="text-foreground">Days 29–30:</strong> compare with normal weekdays. Aim for 20 additional orders, stay within $300, and continue only if the economics and workload justify it. A tracking code alone does not prove the orders were incremental.</li></ol></div>
          <p className="text-sm text-muted-foreground border-t pt-5">That is the combination: a skill guides the work, MCP supplies real local context, and your AI helps turn it into drafts and decisions. You verify details, approve the plan and take action.</p>
          <a href="#setup" className="btn-primary inline-flex">Try it with your AI tool</a>
        </div>
      </details>
    </div>
  </section>;
}
