export default function LocalDataExample() {
  return <section className="container px-4 pt-8 md:pt-16">
    <div className="max-w-5xl mx-auto">
      <p className="text-xs uppercase tracking-wider text-brand-teal font-medium mb-3">Local knowledge, practical action</p>
      <h2 className="text-2xl md:text-3xl mb-4">Connect your AI to the businesses around you</h2>
      <p className="text-muted-foreground leading-relaxed max-w-3xl">The Startup Orillia MCP gives your AI access to our playbooks and local business information, so it can help you find potential partners, discover suppliers and prepare for events—not just suggest generic ideas.</p>
      <div className="grid sm:grid-cols-3 gap-2 sm:gap-4 mt-5 md:mt-7">
        {[
          ["500+", "local businesses", "Search names, services, descriptions and published website links."],
          ["190+", "business categories", "Explore suppliers and potential partners by the work they do."],
          ["Local events", "with source links", "Look up dates and details captured from the public calendar."],
        ].map(([value, label, description]) => <div key={value} className="rounded-2xl border bg-card p-4 md:p-6 grid grid-cols-[7rem_1fr] sm:block items-center gap-x-3"><div><p className="font-heading text-2xl md:text-3xl text-brand-teal font-semibold mb-1">{value}</p><p className="text-sm sm:text-base font-medium sm:mb-3">{label}</p></div><p className="text-sm text-muted-foreground leading-relaxed">{description}</p></div>)}
      </div>
      <p className="text-xs italic text-muted-foreground leading-relaxed mt-4">Snapshots are refreshed regularly. This is not a directory of every business in the area.</p>

    </div>
  </section>;
}

export function EndToEndExample() {
  return <details id="real-example" className="rounded-2xl border bg-card mt-7 group scroll-mt-24">
        <summary className="cursor-pointer p-4 md:p-6 font-heading text-lg md:text-xl font-semibold text-brand-orange">See an example: a bakery finds possible office customers</summary>
        <div className="px-6 pb-6 md:px-8 md:pb-8 space-y-7">
          <p className="font-medium text-sm leading-relaxed">A business problem → real local listings → an offer and message → a 30-day test.</p>
          <p className="text-sm text-muted-foreground leading-relaxed">A worked example using the Startup Orillia MCP and skills, with real local search results from September 17, 2026. This shows how a campaign could work, not one that has already happened. The bakery, budget and sales goals are made up for this example. The named businesses have real listings, but have not agreed to take part.</p>
          <div><h3 className="font-heading text-lg font-semibold mb-2">1. Start with the business problem</h3><blockquote className="rounded-lg bg-secondary p-4">“I run a bakery in Orillia. January weekdays are slow. Help me increase sales.”</blockquote><p className="text-sm text-muted-foreground mt-3">Your AI reads the Local Marketing Campaign skill. It asks whether you can deliver and what you can spend. For this example, assume you can make a few nearby morning deliveries and have a $300 test budget. The goal: five paid office orders in 30 days, with at least two customers ordering again.</p></div>
          <div><h3 className="font-heading text-lg font-semibold mb-2">2. Find businesses with a reason to order</h3><p className="text-sm text-muted-foreground mb-4">Instead of asking people to change their morning routine, offer something for an existing occasion: breakfast for a team meeting or a client visit. The AI searches for local offices. Searches for “accounting” and “insurance” through the Startup Orillia MCP returned these real businesses:</p><div className="grid md:grid-cols-2 gap-4">
            <article className="rounded-xl border p-4"><p className="text-xs uppercase tracking-wide text-brand-teal mb-2">From the business listing</p><h4 className="font-semibold mb-2">Brock-Simcoe Accounting</h4><p className="text-sm text-muted-foreground mb-3">Listed in Orillia under Accounting &amp; Bookkeeping.</p><a href="https://business.orillia.com/list/member/brock-simcoe-accounting-orillia-240" target="_blank" rel="noreferrer" className="text-sm text-brand-orange underline">Read the official listing</a></article>
            <article className="rounded-xl border p-4"><p className="text-xs uppercase tracking-wide text-brand-teal mb-2">From the business listing</p><h4 className="font-semibold mb-2">McDougall Insurance &amp; Financial</h4><p className="text-sm text-muted-foreground mb-3">Listed in Orillia under Insurance.</p><a href="https://business.orillia.com/list/member/mcdougall-insurance-financial-74" target="_blank" rel="noreferrer" className="text-sm text-brand-orange underline">Read the official listing</a></article>
          </div><p className="text-sm text-muted-foreground mt-3">These are businesses to research, not confirmed customers. The listings do not tell us their team size, meeting schedule or whether they buy food. First check their location and ask whether they ever order breakfast for meetings. Chamber membership is not an endorsement or quality rating.</p></div>
          <div><h3 className="font-heading text-lg font-semibold mb-2">3. Say “Build the office breakfast idea”</h3><p className="text-sm text-muted-foreground leading-relaxed">The AI builds a simple offer: a box of 12 muffins and pastries, ordered the day before, ready for a weekday meeting. Offer pickup or delivery within a small area if the costs work. Set the price after adding up ingredients, packaging, staff time and delivery. Include ingredients and allergen information. Start with two delivery slots a day, rather than promising more than you can manage.</p></div>
          <div><h3 className="font-heading text-lg font-semibold mb-2">4. Get drafts you can actually use</h3><p className="text-sm font-medium mb-2">A first message for you to review and send through an appropriate business contact</p><blockquote className="rounded-lg bg-secondary p-4 text-sm leading-relaxed">Hi Brock-Simcoe team—I'm the owner of [bakery] in Orillia. Do you ever order breakfast for team meetings or client visits? We're testing a box of 12 muffins and pastries that can be ordered the day before, with weekday pickup or nearby delivery. If that's useful, may I send you the menu and prices?</blockquote><p className="text-sm font-medium mt-4 mb-2">A short offer for your website or menu</p><p className="text-sm text-muted-foreground">“Breakfast for your next meeting. A box of 12 muffins and pastries for [price]. Order by [time] the day before. Weekday pickup or delivery in [area] for [fee]. See ingredients and allergen information at [link].”</p></div>
          <div><h3 className="font-heading text-lg font-semibold mb-2">5. Leave with a 30-day plan and a decision</h3><ol className="list-decimal pl-5 space-y-2 text-sm text-muted-foreground"><li><strong className="text-foreground">Days 1–7:</strong> price the box, check delivery costs and make a short menu. Research ten nearby offices and check whether they order food for meetings.</li><li><strong className="text-foreground">Days 8–14:</strong> share the offer with interested businesses. Take a few paid trial orders and ask whether the food, timing and price worked for them.</li><li><strong className="text-foreground">Days 15–28:</strong> invite satisfied customers to order for their next meeting. Track orders, sales, food and delivery costs, and staff time. Do not keep contacting businesses that decline.</li><li><strong className="text-foreground">Days 29–30:</strong> did you get five paid office orders and two repeat customers? Did each order leave enough money after costs to make the work worthwhile? Stay within the $300 test budget. If delivery costs too much, test pickup only; if there is little interest, stop and try a different offer.</li></ol></div>
          <p className="text-sm text-muted-foreground border-t pt-5">That is the combination: a skill guides the work, the Startup Orillia MCP provides local information, and your AI helps turn it into drafts and decisions. You check the details, approve the plan and take action.</p>
          <a href="#setup" className="btn-primary inline-flex">Try it with your AI tool</a>
        </div>
      </details>;
}
